# Generated by Django 2.2.7 on 2019-12-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('single', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='target',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
