# Generated by Django 2.2.7 on 2019-12-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('single', '0002_auto_20191208_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
