# Generated by Django 2.2.7 on 2019-12-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('single', '0003_auto_20191209_0112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
