name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        rm test.py
        python -m pip install --upgrade pip
        pip install django django-progressive-web-app
    - name: Test
      run: |
        python3 manage.py test
